### ISSUE TITLE
The examples mostly don’t work and are hard to understand.

### ISSUE THREAD

**Issue by JoseGuilherme1904** [meta-llama/llama-stack-apps#101]
### 🚀 The feature, motivation and pitch

I insist on trying to learn and study the llama-stack API and its examples, but they are complex. There’s no documentation, or I’m unable to access it.

I watched all the course videos:
https://learn.deeplearning.ai/courses/introducing-multimodal-llama-3-2/lesson/7/tool-calling

While I understood the lessons, I feel lost applying them locally. The course seemed to end before diving into llama-stack.

How can I use the following API calls?

Serving API telemetry
GET /telemetry/get_trace
POST /telemetry/log_event

Serving API models
GET /models/get
GET /models/list
POST /models/register

Serving API scoring
POST /scoring/score
POST /scoring/score_batch

Serving API datasets
GET /datasets/get
GET /datasets/list
POST /datasets/register

Serving API inference
POST /inference/chat_completion
POST /inference/completion
POST /inference/embeddings

Serving API agents
POST /agents/create
POST /agents/session/create
POST /agents/turn/create
POST /agents/delete
POST /agents/session/delete
POST /agents/session/get
POST /agents/step/get
POST /agents/turn/get

Serving API inspect
GET /health
GET /providers/list
GET /routes/list

Serving API scoring_functions
GET /scoring_functions/get
GET /scoring_functions/list
POST /scoring_functions/register

Serving API memory
POST /memory/insert
POST /memory/query

Serving API eval
POST /eval/evaluate
POST /eval/evaluate_batch
POST /eval/job/cancel
GET /eval/job/result
GET /eval/job/status

Serving API memory_banks
GET /memory_banks/get
GET /memory_banks/list
POST /memory_banks/register

Serving API shields
GET /shields/get
GET /shields/list
POST /shields/register

Serving API datasetio
GET /datasetio/get_rows_paginated

I’ve been trying to study this Meta project for three months, but without clear documentation, it’s frustrating. If anyone here works with Meta or can offer guidance, I would greatly appreciate the help.

### Alternatives

python examples/memory/client.py localhost 5000
 
Traceback (most recent call last):
  File "/home/guilherme/angular/llama/llama-stack-apps/examples/memory/client.py", line 131, in <module>
    fire.Fire(main)
  File "/home/guilherme/.local/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/guilherme/.local/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/guilherme/.local/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/guilherme/angular/llama/llama-stack-apps/examples/memory/client.py", line 127, in main
    asyncio.run(run_main(host, port, stream))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/guilherme/angular/llama/llama-stack-apps/examples/memory/client.py", line 40, in run_main
    providers = client.providers.list()
AttributeError: 'LlamaStackClient' object has no attribute 'providers'

### Additional context

python -m examples.agents.vacation localhost 5000
> created agents with agent_id=cbe4fa59-0601-484b-b47d-20225256a130
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/guilherme/angular/llama/llama-stack-apps/examples/agents/vacation.py", line 58, in <module>
    fire.Fire(main)
  File "/home/guilherme/.local/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/guilherme/.local/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/guilherme/.local/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/guilherme/angular/llama/llama-stack-apps/examples/agents/vacation.py", line 54, in main
    asyncio.run(run_main(host, port, disable_safety))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/guilherme/angular/llama/llama-stack-apps/examples/agents/vacation.py", line 37, in run_main
    await execute_turns(
  File "/home/guilherme/angular/llama/llama-stack-apps/examples/agents/multi_turn.py", line 40, in execute_turns
    agent = await get_agent_with_custom_tools(
  File "/home/guilherme/angular/llama/llama-stack-apps/common/client_utils.py", line 190, in get_agent_with_custom_tools
    session_response = client.agents.session.create(
AttributeError: 'AgentsResource' object has no attribute 'session'. Did you mean: 'sessions'?

**Comment by heyjustinai** [comment]
No response for a long time, so closing this issue. Feel free to reopen or create a new one if needed, thanks!
