### ISSUE TITLE
StepType

### ISSUE THREAD

**Issue by JoseGuilherme1904** [meta-llama/llama-stack-apps#62]
Please, I need help.

mesop ./app/main.py 
Traceback (most recent call last):
  File "/tmp/a/llama/conda/envs/app_env/bin/mesop", line 8, in <module>
    sys.exit(run_main())
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/bin/bin.py", line 285, in run_main
    app.run(main)
  File "/home/xxxxx/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/xxxxx/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/bin/bin.py", line 99, in main
    app = create_app(
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/server/wsgi_app.py", line 39, in create_app
    run_block()
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/bin/bin.py", line 101, in <lambda>
    run_block=lambda: execute_main_module(absolute_path=absolute_path),
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/bin/bin.py", line 272, in execute_main_module
    raise e
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/bin/bin.py", line 262, in execute_main_module
    execute_module(
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/cli/execute_module.py", line 12, in execute_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/a/llama/llama3.1/llama-stack-apps-main/./app/main.py", line 9, in <module>
    from utils.chat import chat, State
  File "/tmp/a/llama/llama3.1/llama-stack-apps-main/./app/utils/chat.py", line 19, in <module>
    from llama_toolchain.agentic_system.api.datatypes import StepType
ModuleNotFoundError: No module named 'llama_toolchain.agentic_system.api.datatypes'

**Comment by ashwinb** [comment]
Thanks Jose. Looks like one of our refactors caused this. I will fix this imminently.

**Comment by ashwinb** [comment]
https://github.com/meta-llama/llama-stack-apps/commit/0e8dd7c261d7b0ca01c5d87d671896d72292a59b

Should be fixed. Let me know if not.

**Comment by JoseGuilherme1904** [comment]
Thank you, please, we have now new problem
mesop app/main.py
Traceback (most recent call last):
  File "/tmp/a/llama/conda/envs/app_env/bin/mesop", line 8, in <module>
    sys.exit(run_main())
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/bin/bin.py", line 285, in run_main
    app.run(main)
  File "/home/guilherme/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/guilherme/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/bin/bin.py", line 99, in main
    app = create_app(
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/server/wsgi_app.py", line 39, in create_app
    run_block()
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/bin/bin.py", line 101, in <lambda>
    run_block=lambda: execute_main_module(absolute_path=absolute_path),
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/bin/bin.py", line 272, in execute_main_module
    raise e
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/bin/bin.py", line 262, in execute_main_module
    execute_module(
  File "/tmp/a/llama/conda/envs/app_env/lib/python3.10/site-packages/mesop/cli/execute_module.py", line 12, in execute_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/a/llama/llama3.1/llama-stack-apps-main/app/main.py", line 9, in <module>
    from utils.chat import chat, State
  File "/tmp/a/llama/llama3.1/llama-stack-apps-main/app/utils/chat.py", line 93, in <module>
    class StepStatus:
  File "/tmp/a/llama/llama3.1/llama-stack-apps-main/app/utils/chat.py", line 95, in StepStatus
    content: Union[InterleavedTextAttachment, ShieldResponse]
NameError: name 'InterleavedTextAttachment' is not defined

**Comment by ashwinb** [comment]
Yeah, fixing haha. Sorry!

**Comment by ashwinb** [comment]
https://github.com/meta-llama/llama-stack-apps/commit/5394b01e6e5ebb638a0e1b7d4638e99e0c423c1a

**Comment by JoseGuilherme1904** [comment]
Thank you so much!
