### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_toolchain.memory.common'

### ISSUE THREAD

**Issue by JoseGuilherme1904** [meta-llama/llama-stack-apps#73]
llama stack run /home/guilherme/.llama/builds/local/conda/8b-instruct.yaml --port 5000 --disable-ipv6
Valor de args.config: /home/guilherme/.llama/builds/local/conda/8b-instruct.yaml
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1

/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/site-packages/torch/__init__.py:955: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
Loaded in 29.10 seconds
Finished model load YES READY
Traceback (most recent call last):
  File "/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/site-packages/llama_toolchain/core/server.py", line 372, in <module>
    fire.Fire(main)
  File "/home/guilherme/.local/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/guilherme/.local/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/guilherme/.local/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/site-packages/llama_toolchain/core/server.py", line 320, in main
    impls = resolve_impls(provider_specs, config)
  File "/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/site-packages/llama_toolchain/core/server.py", line 293, in resolve_impls
    impl = instantiate_provider(provider_spec, provider_config, deps)
  File "/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/site-packages/llama_toolchain/core/dynamic.py", line 39, in instantiate_provider
    impl = asyncio.run(fn(config, deps))
  File "/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/site-packages/llama_toolchain/memory/meta_reference/faiss/__init__.py", line 11, in get_provider_impl
    from .faiss import FaissMemoryImpl
  File "/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/site-packages/llama_toolchain/memory/meta_reference/faiss/faiss.py", line 19, in <module>
    from llama_toolchain.memory.common.vector_store import (
ModuleNotFoundError: No module named 'llama_toolchain.memory.common'

**Comment by JoseGuilherme1904** [comment]
conda activate llamastack-8b-instruct
pip uninstall llama_toolchain
pip install llama_toolchain

 llama stack run /home/guilherme/.llama/builds/local/conda/8b-instruct.yaml --port 5000 --disable-ipv6
Valor de args.config: /home/guilherme/.llama/builds/local/conda/8b-instruct.yaml
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/tmp/a/llama/conda/envs/llamastack-8b-instruct/lib/python3.10/site-packages/torch/__init__.py:955: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
Loaded in 14.57 seconds
Finished model load YES READY
Serving POST /inference/chat_completion
Serving POST /inference/completion
Serving POST /inference/embeddings
Serving POST /memory_banks/create
Serving DELETE /memory_bank/documents/delete
Serving DELETE /memory_banks/drop
Serving GET /memory_bank/documents/get
Serving GET /memory_banks/get
Serving POST /memory_bank/insert
Serving GET /memory_banks/list
Serving POST /memory_bank/query
Serving POST /memory_bank/update
Serving POST /safety/run_shields
Serving POST /agentic_system/create
Serving POST /agentic_system/session/create
Serving POST /agentic_system/turn/create
Serving POST /agentic_system/delete
Serving POST /agentic_system/session/delete
Serving POST /agentic_system/session/get
Serving POST /agentic_system/step/get
Serving POST /agentic_system/turn/get
Serving GET /telemetry/get_trace
Serving POST /telemetry/log_event
Listening on 0.0.0.0:5000
INFO:     Started server process [28556]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)

**Comment by yanxi0830** [comment]
Thanks for raising the issue! This should be fixed with https://github.com/meta-llama/llama-stack/blob/main/llama_toolchain/memory/common/__init__.py. Closing, please re-open if you still encounter similar issue.
