### ISSUE TITLE
llama_stack_client.PermissionDeniedError: Error code: 403 after running PYTHONPATH=. mesop app/main.py

### ISSUE THREAD

**Issue by frieda-huang** [meta-llama/llama-stack-apps#88]
Running it on 
- Mac M2
- Ollama
- Llama3.1-8B-Instruct
- Llama-Guard-3-8B

```
I1005 20:37:58.358263 8372277056 _client.py:1038] HTTP Request: POST http://localhost:5000/agents/create "HTTP/1.1 403 Forbidden"
Traceback (most recent call last):
  File "/opt/anaconda3/envs/llamastack-my-local-stack/bin/mesop", line 8, in <module>
    sys.exit(run_main())
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/mesop/bin/bin.py", line 285, in run_main
    app.run(main)
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/mesop/bin/bin.py", line 99, in main
    app = create_app(
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/mesop/server/wsgi_app.py", line 37, in create_app
    run_block()
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/mesop/bin/bin.py", line 101, in <lambda>
    run_block=lambda: execute_main_module(absolute_path=absolute_path),
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/mesop/bin/bin.py", line 272, in execute_main_module
    raise e
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/mesop/bin/bin.py", line 262, in execute_main_module
    execute_module(
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/mesop/cli/execute_module.py", line 12, in execute_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/friedahuang/Documents/llama-stack-apps/app/main.py", line 16, in <module>
    client_manager.init_client(
  File "/Users/friedahuang/Documents/llama-stack-apps/app/utils/client.py", line 46, in init_client
    self.client = asyncio.run(
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/friedahuang/Documents/llama-stack-apps/common/client_utils.py", line 183, in get_agent_with_custom_tools
    create_response = client.agents.create(
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack_client/resources/agents/agents.py", line 110, in create
    return self._post(
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack_client/_base_client.py", line 1251, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack_client/_base_client.py", line 943, in request
    return self._request(
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack_client/_base_client.py", line 1046, in _request
    raise self._make_status_error_from_response(err.response) from None
llama_stack_client.PermissionDeniedError: Error code: 403
```

**Comment by frieda-huang** [comment]
It's now working. Turns out I need to match the port number to that of the llama stack in llama-stack-apps/app/utils/common.py:

`DISTRIBUTION_PORT = os.environ.get("DISTRIBUTION_PORT", 11434)`

**Comment by yanxi0830** [comment]
Awesome! FYI the mesop app have been deprecated recently to be replaced with gradio app (Better!) for chat agent here: (https://github.com/meta-llama/llama-stack-apps/tree/main/examples/agent_store)
